FROM justsong/one-api
EXPOSE 3000
ENV PORT 3000
ENV BATCH_UPDATE_ENABLED=true
ENV BATCH_UPDATE_INTERVAL=120
ENV GLOBAL_WEB_RATE_LIMIT=300
ENV GLOBAL_API_RATE_LIMIT=900

WORKDIR /data
RUN mkdir /data/logs && chmod 777 /data/logs
ENTRYPOINT ["/one-api"]